<footer>
		<h1><img src="images/bottom_bi.png" alt="그린베이커리 Bi"></h1>
		<p>인천광역시 부평구 길주로 623, 108호 (삼산동, 대덕리치아노)<br><a href="tel:032-363-2505">전화번호: 032-363-2505</a><br>Copyrightⓒ 2016 Green Bakery.  All rights reserved.</p>
		<ul>
			<li><a href="https://www.youtube.com"><img src="images/ico_social_1.png" alt="유튜브 아이콘"></a></li>
			<li><a href="https://ko-kr.facebook.com/"><img src="images/ico_social_2.png" alt="페이스북 아이콘"></a></li>
			<li><a href="https://twitter.com/?lang=ko"><img src="images/ico_social_3.png" alt="트위터 아이콘"></a></li>
			<li><a href="https://www.instagram.com/"><img src="images/ico_social_4.png" alt="인스타그램 아이콘"></a></li>
		</ul>
</footer>