<nav>
	<h2>내비게이션</h2>
		<ul data-role="page">				
			<li><a href="index.html">&lt;  MAIN</a></li>
			<li><a href="brand_story.html" rel="external">브랜드 스토리</a></li>
			<li><a href="menu.html">메뉴</a></li>
			<li><a href="baking.html">베이킹 클래스</a></li>
			<li><a href="greens_story.html">Green's 이야기</a></li>
		</ul>
</nav>
<div id="full_black"></div>
	<header>
		<h2>그린 베이커리 상단</h2>		
		<ul>
			<li><img src="images/ico_nav_list.png" alt="네비게이션 목록"></li>
			<li><a href="index.html"><img src="images/top_bi.png" alt="상단로고"></a></li>
		</ul>
</header>